### ISSUE TITLE
news posting - revision box docs

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#13]
test user - need explanation of the revision information box - what does each one mean.

**Comment by djwesto** [comment]
Hi @GilesGibson I need more detail on this because it's Issue #13 which was originally written in Nov 2013, are you referring to the actual wording of these messages?

![screenshot 2015-01-27 18 27 08](https://cloud.githubusercontent.com/assets/702685/5924251/23d99700-a652-11e4-9f0d-d71012fbec86.png)

![screenshot 2015-01-27 18 26 00](https://cloud.githubusercontent.com/assets/702685/5924240/0c1434a4-a652-11e4-9d3c-3332fb4a180e.png)

If not, could you provide a screengrab of what it was you were talking about?

**Comment by GilesGibson** [comment]
lets leave this. Was ages ago and the site is very different now.
