### ISSUE TITLE
improve theming of user page

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#318]
a news item is awaiting moderation. I checked in the "my account" page. Nothing listed. Not sure if we are listing the users content and progress but it would be good to do so.

Bottom of screen did have an area for user menu but the buttons were not working, just a drop-down arrow.

![image](https://cloud.githubusercontent.com/assets/6060985/5267655/9cc7d868-7a4a-11e4-9d53-63ac3087540d.png)

**Comment by djwesto** [comment]
So, again, there are a lot of separate tasks arising from this one issue. To deal with @GilesGibson's question first: The **"Recent Content"** table shows content that's already published. So the status of all the items on that list is "Published". See my comment below about how this label should be changed to "Recently published content" to help clarify this.

Also, please note that your user page only displays content which you have created – not all site content. @pmackay Is there any way we could edit the fields displayed in this table to also possibly include the content type of each item? News article, Event, Group post etc?

The Users section of the site is actually quite extensive if we include all the tabs:
![screenshot 2015-01-13 11 11 52](https://cloud.githubusercontent.com/assets/702685/5719911/029dd2c4-9b15-11e4-83f5-c1ebfff3fb76.png)

Once you take out those tabs which won't appear to non-admins, you're still left with:

Section label | Explanation | Needs style fixes
------------ | ------------- | -------------
**View** | This tab currently serves as a "My Content" listing. Changing the label to "My content" might help explain this function better. Also, the heading label for the second "Recent content" would be clearer if changed to "Recently published content". | YES
**Edit** | This is where users can edit their details. The label is reasonably clear although "Edit details" might help. | NO
**Messages** | This is basically another table that needs some more consistent styling | YES
**My follow links** | Headings on this grid of fields need fixes. In addition, the following text appears on this page ""Please copy and paste the url for your public profile or page for each service you would like to display in the block. Links need to match the domain of the service in question." – this needs to be rewritten because the term "block" won't mean anything to most users. In fact, I'm not even sure where such a block even appears. | YES
**Connections** | Still searching for info on what this even does. Possibly could be hidden. | UNKNOWN
**Contact** | Basically working although we might sharpen up the layout a bit if we have time. | MAYBE
**Photo albums** | We will be adding in another tab for users' albums of images. | YES

NB. Panelizer and Devel only appear to admins.

So, here are the tasks I see we need to do for the User page:
* @GilesGibson decide if there's any other info you want people to see on a User's profile page (eg. consider if we want users to be able to view info about other users)
* Create style definitions for **DT** and **DD** elements used to define the User's history info on the View page.
* Fix the table styling on all tab screens including typography, alignment and general table presentation.
* Try to fix the misleading label text somehow (either with String Overrides module or tpl.php override files?
* @pmackay Let me know if there was anything in that User menu you hid from displaying that was important?

**Comment by GilesGibson** [comment]
I think at this stage we need to keep it simple but effective and useful. A user may want to find the comment or news item they write ages ago, to refer to it again in another comment or event etc. Having a simple list that they can either get an instant link added to their clipboard or just click and go to that item again would be useful. Knowing what the status is of anything they have contributed to as well is also key. They may have written/submitted a news item that is still waiting on moderation - being able to list all those passed/waiting etc would be great. If we can provide more info about that item (or any item they have contributed) would be good - the edit date, title, status. 

The ability to search for a user will be more and more important as Connecting Communities starts to come on board. Searching user profiles for tags/keywords is important. Maybe searching their content as well but that should be under the general site search feature. If it found a news item then clicking on the user name would then show all the items that the user had contributed. That would help make the "connection" to the right user (or group?).

**Comment by djwesto** [comment]
Thanks for this @GilesGibson.

* If authors want to find an item of content they wrote ages ago, they _can_ refer to these tables in their user profile. We'll do our best to improve them before launch.
* I understand authors want to know the status of content they've created. I'll work with @pmackay to see if we can create a pair of tables (possibly each in a separate tab): one for recently published content and another for all their content which can be viewed with its publication status, edit date, title etc.
* Yesterday, Paul pointed out that this is quite complex when you take into account that a content item might have been published but be being reviewed as well or even be in a second draft so this isn't a binary thing.
* Now, on your idea for authors having to click a button to copy-paste a link to something they've already created so they can embed it in a new post... We actually already have a tool called _Linkit_ built into the site which we think does a better job than that. When you want to add a link to an existing piece of content to your new post, all you do is click the Link button in the toolbar at the top of the content editor, and start typing the name of the piece of content you are looking for. Here's a screengrab of it working:

![screenshot 2015-01-14 11 32 45](https://cloud.githubusercontent.com/assets/702685/5738163/195ab29e-9be1-11e4-81c2-c44b7017e53b.png)

* Your point about viewing content which other users have created is worth exploring since it is an adaptation of the existing user profile page but exposed for other users to view. @pmackay can we review? Is this simply a permissions issue or would it require a lot of re-configuration time? 
* Related to this, @GilesGibson, can we assume you didn't think of any other detail you'd want to see appearing on a user's profile page?

**Additional issues**
You've raised several issues that'll need to be pushed to the backlog for the time-being as they constitute tasks which should be done under a Connecting Communities workstream:
1. The ability to search for a user (which will be more and more important as Connecting Communities starts to come on board).
2. Searching user profiles for tags/keywords (and presumably also **Skills** and **Interests**?)

We think both of these ideas have real merit and we would love to explore them. But they weren't technically in the original brief for HH so we'd like to ask you to create each of them as new (separate) GH issues and also add as much detail as you can about the user stories which might involve searching for a user and how it might all work.

Then we can backlog them for the timebeing. Obviously, these are critical to the CC project so we'd push them straight into a first iteration of CC as soon as we can.

**Comment by GilesGibson** [comment]
OK about pushing some of the user profile stuff to the backlog. Just as long as we don't design out the feature in the short term and then make more work for us to enable it later.

Re: Linkit - yes I think I was aware of that, came up in previous github issues - the name is not very user intuitive so I think we had suggested changing the text prompt that come up next to the button.

Re: tracking user content. To avoid support hassles the user really does nee to know the status of their creations. Even if it had been published, then edited and therefore re-submitted for publication the user needs to know where in the process it had got to.

**Comment by pmackay** [comment]
We can check view permissions of those views. If they are moved to separate
tabs, will it result in too many tabs? Maybe not a big deal.

**Comment by pmackay** [comment]
please please please do create new issues for discussing stuff though, much
easier to track. This issue is about theming the user page.

Thanks!

**Comment by djwesto** [comment]
I don't think there's any problem right now with too many tabs. On my **chriswells** account I think I only have 3-4 visible.

**Comment by pmackay** [comment]
What would the main user page show if both those tables are moved to
separate tabs?

**Comment by djwesto** [comment]
Sorry, wasn't clear with that comment – the reason I suggested two tabs was to avoid the problem with paginating two views on one page but I didn't mean adding two new tabs.

I just meant that one solution might be perhaps that the tab currently labelled "View" could become the "Recently published content" tab (essentially a Facebook wall style stream of content, similar to what appears on the homepage) and that we might also create a new tab for "All my content" which would be a more sortable, filterable table view. 

But I wonder if there's a possible one-tab solution which would involve just building the single table with sortable columns and filters but which shows all content (perhaps with pagination). However, I know you said there's a problem with published content which is being redrafted showing up...?

**Comment by GilesGibson** [comment]
happy with a couple of tabs - this provides a "pre-filter" that we have done on behalf of the user - content awaiting publication", "content published".

**Comment by pmackay** [comment]
There is now a "Published content" tab with a table there, visible to all. Draft content still on user page but should only be visible to that user. Can any other aspects to this go to backlog?

**Comment by GilesGibson** [comment]
OK, I can see the two sections, I assume you eman this:

![image](https://cloud.githubusercontent.com/assets/6060985/5763858/bc238e4c-9ce5-11e4-9467-ce6505b07757.png)


Couldn't see the two tabs, just two tables. The fist table may get quite long and push down the other table too far. Can we have two tabs and flip between each one?

**Comment by djwesto** [comment]
Nope. Go to http://dev-hernehill.gotpantheon.com/user and you should see something like this:

![screenshot 2015-01-15 18 43 00](https://cloud.githubusercontent.com/assets/702685/5763949/68ecba68-9ce6-11e4-8106-b89d17887f97.png)

**Comment by GilesGibson** [comment]
The user standarduser isn't on that site, only live.

**Comment by djwesto** [comment]
If you visit http://dev-hernehill.gotpantheon.com/user and log in as admin, you'll be able to see the Published Content tab.

**Comment by pmackay** [comment]
All changes only being pushed to dev currently.

**Comment by GilesGibson** [comment]
Ah, any idea what logins work for me on dev?

**Comment by djwesto** [comment]
Just emailed you the login details for dev- @GilesGibson.

Also, @pmackay and I have been discussing the two tabs on the User Profile section labelled View and Published Content. Having had a think, I believe that when *I* visit **your** "User Profile" I should see a list of all the content *you've* published next to your profile photo and a brief description of who you are.

This is also the view you'd see if you visit your user profile. And, if you want to see your Drafts, we'd show those in a separate tab.

This makes more sense to me because it means the first tab page is of use to everyone.

**Comment by GilesGibson** [comment]
agree on tabs.

**Comment by pmackay** [comment]
Tabs now switched over. And user page looking a lot better.

**Comment by GilesGibson** [comment]
Draft content needs message if blank.
