### ISSUE TITLE
Gallery - image rotation

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#322]
I uploaded a picture from my desktop - it was the right way up there. The thumbnail showed it 90 degrees out.

![image](https://cloud.githubusercontent.com/assets/6060985/5267939/14319b94-7a4d-11e4-9f4b-6035c2e1b1e4.png)

when I go back in and click on the image file name the preview shows it the right way up.

**Comment by pmackay** [comment]
I think its because its a photo taken vertically. Interesting thread about it here https://www.drupalgardens.com/content/uploading-media-automatically-rotates-images. Best I think we could do is offer some notes on how to correct by resaving the image.

@djwesto got any thoughts on how to improve this?

**Comment by djwesto** [comment]
@pmackay is right – it's caused because the camera was rotated 90degrees to take the portrait shot which is handled by the Finder on your Mac which auto-rotates the image for you. However, Drupal doesn't have that function built in.

I've found a few d.o. topics about this issue. Here's a good one: https://www.drupal.org/node/564424

I get the impression that ImageCache Autorotate sub-module *might* fix this.

However, if @pmackay's reluctant to introduce a new module to fix it, then we'd need to handle this carefully in the field labels and help system.

NB. @GilesGibson, each time we identify the need for a new module, it increases the RAM required to run the site. Might need to have a chat about budgets for hosting...

**Comment by djwesto** [comment]
Re-assigned to @pmackay to research ImageCache sub-module for fixing this.

**Comment by GilesGibson** [comment]
can move to V 1.01
