### ISSUE TITLE
User profile - image upload at 100meg

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#383]
Should we not be limiting the file size uploaded here:

![image](https://cloud.githubusercontent.com/assets/6060985/5285191/199e93b4-7b12-11e4-82a2-b99ddb593e6b.png)

Having avatars at 100meg may slow the system down a tad.

**Comment by djwesto** [comment]
Surely it won't matter if users upload a 100MB image because no image should be displayed at full size on the site – every single image which appears on a page should have been resized and cropped down to the precise size needed to display it at and all other image data thrown away.

The only problem you might encounter is if a lot of users upload a ton of large images direct from their SLR which fill up your server but that's a file storage problem. If Panopoly won't let you adjust the file upload size then that's a real pain and inexplicable but I wouldn't think it's the end of the world – most normal camera users won't be able to generate images which are even close to 10MB, let alone 100.

I suggest this matter can be dropped.

**Comment by GilesGibson** [comment]
Will the site run slow if large images are there? Before we used to wait ages for a page to load, we cut the size of image file down and it was much snappier. Dont want the site to be a crawler, hence the idea of at least stating that 10 meg was the size limit even if it isn't. It may encourage people to upload more refined files.

**Comment by djwesto** [comment]
The site *would* run slow if large images are displayed on pages – large images can take an age to transfer across the web.

Sorry if that last message was a bit unclear. Here's how I see it working in plain terms:

1. A user will upload a large image (for instance, when they add a news story)
2. As soon as they publish the article, the image conversion functions in the site would re-size their original image file down to a set of minimal, fixed sizes: a large featured image size for the story page itself and a few others for other uses, such as showing thumbnail versions in the news listings etc
3. After that, the original file might as well be thrown away because it should never be used again on the site. The only images that should ever appear are the reduced files, specifically optimised for the site.

Displaying gigantic images on a webpage is never a good idea and we'd definitely want to avoid that happening anywhere. That's why we've drawn up the list of Image Styles (sizes) which we're ensuring are applied to every content type on the site.

Does this explain it? If not, a quick Skype call should make it clear as day.

**Comment by GilesGibson** [comment]
no problem with news items then. DO we still store the original file on the server? If so, bit worried about disk thrashing, caching, storage limits etc. 

What happens about galleries? Are they constrained? Will they run slow?

**Comment by djwesto** [comment]
Disk thrashing and caching are something @pmackay needs to address as I'm no expert.

Storage limits for images are a question of how much storage we buy as part of the hosting package.
* How much storage size do you currently have?
* We also need to know roughly how many images the current site holds and roughly how many more (perhaps as a percentage) you are hoping to encourage users to upload.
* Then it's a fairly rudimentary back-of-the-envelope calculation to work out how much space we should plan for, along with a contingency.

As with my earlier reply, images uploaded to Galleries (like every other image uploaded to the site) should be re-resolved to specific smaller, fixed dimensions.

**Comment by GilesGibson** [comment]
OK, if we are changing the image file size for galleries as well then we should be fine. Can we set the size that we are reducing to? Be good to have some reasonable quality there without it taking weeks to load on the average broadband.

**Comment by djwesto** [comment]
@pmackay I've realised we need a new Image Style for Gallery Images... Might need to chat with you about the best way to optimise these since we'd presumably want them to be fairly large and full width...

**Comment by pmackay** [comment]
@djwesto please update your image style table as needed.

**Comment by djwesto** [comment]
Just checked – great to see that fixed. Does that mean you changed some stylesheets or was it that you removed the code from when we had the help text stuff in that area?

![screenshot 2015-01-15 22 51 51](https://cloud.githubusercontent.com/assets/702685/5768476/20e97922-9d09-11e4-9acb-098e1949711b.png)

**Comment by pmackay** [comment]
@djwesto I think your last comment is related to a different issue, but it was fixed in 5fa4cee47290cfcf70047d82ef10a502dea0cb98.

**Comment by pmackay** [comment]
User profile image now limited to 5MB.
