### ISSUE TITLE
Un-hide the date & time field help text on Events content type

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#4]
The layout of the start date/end date is confusing. We need to step people through the process with a help box next to each item with examples. Start date needs to say just that - "please enter the date of the event and the start time". Next box would be "the time the event finishes i.e. an hour later".

**Comment by djwesto** [comment]
So I've taken a look at this (Issue #4 no less!) and discovered that it's quite tough to add in help text next to every single field item to explain what they're for. So I've changed the field group title explain what it's for "Please enter a start and end date and time for this event":

![screenshot 2015-01-27 14 15 04](https://cloud.githubusercontent.com/assets/702685/5919790/09da5c04-a62f-11e4-8c22-f414f51b8500.png)

@GilesGibson are you happy for us to close this now?

**Comment by GilesGibson** [comment]
The biggest support hassle we get is with entering the date and time for an event. The issue is for people who do a series of events, such as yoga classes. They think that the end date is the last date on the course, as it is called "date". We really need some text next to the fields or far more help above the fields to stop the endless errors. It is a UX issue that drives us round the bend.

**Comment by djwesto** [comment]
OK. That'll take a bit more work to tweak the template. @pmackay, can we discuss this? Is it a particular -tpl.php file I can work on?

**Comment by djwesto** [comment]
@pmackay I'm actually going to re-assign this to you because we have the extensive help text in the Events content type but it's not currently displaying. If you can get that fixed and we can pass it by @GilesGibson again, perhaps that'll put this to rest. Otherwise, we'll need to look at each individual field label and re-write them.

**Comment by GilesGibson** [comment]
I suppose we need a simple flow chart approach to how the info is laid out.

Step 1:

What is the date of your event?
(If it is a series of events then please enter the date that the first event is on)

Step 2:
What time does it start?

Step 3:

What time does it finish?

Step 4:

If the event lasts longer than the day it starts on (i.e. runs past midnight) then please edit the finish date box (otherwise leave it as the same date as the start date). *we need to pre-load the box with the same data as the start date*.

Step 5:

If there is more than one occurrence of this event - it may be a course of one evening a week over a period of weeks then choose "recurring event". If it is a one off event then please leave unchecked.

Step 6:
*only shown if recurring event selected*
Please enter the last date on which this event or series of events will be taking place:

**Comment by pmackay** [comment]
Description was hidden due to a bug in date repeat: https://www.drupal.org/node/2186191. Will apply patch.

**Comment by pmackay** [comment]
Description now visible here http://dev-hernehill.gotpantheon.com/node/add/ol-event. @GilesGibson please check, close if ok.

**Comment by GilesGibson** [comment]
OK, good to see the text back. I fear that this issue will crop up again, it has been one of the toughest support issues we have faced and one mistake by a user just spams the entire what's On section with duplicate events.

**Comment by djwesto** [comment]
Can you please check these tweaks to the wording of the help text. I've checked the actual label text on the Date and time details panel and this might make it a bit easier to understand. If you approve it, @GilesGibson, then I'll make the changes.

===
**How to set the date and time for one-off or repeating events**
The "Start date" of your event is the day and time your event begins.
Please also click "Show End Date" and set the day and time your FIRST event ends (i.e. perhaps one hour after it started).

To create a repeating event like a weekly meeting, please click the "Repeat" check box at the bottom of this panel. Next, choose when your event repeats from the Repeats dropdown menu (Daily, Weekly, Monthly etc) and choose which day, week or month it repeats on. Don't forget to enter the date your series finishes (otherwise it will repeat until the end of time!)

Please check your entry before saving it then review the What's On calendars to check where your event is listed and ensure it only repeats on the correct dates.

===

**Comment by GilesGibson** [comment]
Happy to go with your revised wording.

**Comment by djwesto** [comment]
![screenshot 2015-01-29 12 29 45](https://cloud.githubusercontent.com/assets/702685/5957538/b2c012bc-a7b2-11e4-9c63-504152a02548.png)

**Comment by GilesGibson** [comment]
lets see how it goes.

**Comment by djwesto** [comment]
Please check you're happy with this on the dev- site now.

**Comment by GilesGibson** [comment]
Is the "show end date" box going to be checked by default?

**Comment by pmackay** [comment]
Do you want it to be?

**Comment by GilesGibson** [comment]
I think so, people then know how going the event/meeting is going to be.
