### ISSUE TITLE
review layout of Venues page

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#466]

**Comment by djwesto** [comment]
Just pushed a change to the layout of the Venues page – much better arrangement of page elements, with large full-width map and the venue listing now sits wider in the central column, flanked by the explanatory text and the controls.

![screenshot 2015-01-27 16 50 36](https://cloud.githubusercontent.com/assets/702685/5922606/e53f960a-a644-11e4-94f2-59b87d5b5c78.png)

Waiting for sign-off, @GilesGibson

**Comment by GilesGibson** [comment]
this is what I get for events map, just a blank.

![image](https://cloud.githubusercontent.com/assets/6060985/5923333/abc59900-a64a-11e4-9d70-1add54dea821.png)

**Comment by GilesGibson** [comment]
On the venues page. The venues look like they will be listed down the centre column. Over a period of time this will get longer and longer. 

How will we manage this?

If someone clicks on a pin what should happen? The full listing of that venue come to the top of the list? If they double clicked it what should it show? I would assume that the user wanted more info about the venue (opening times for instance). Can we show more?

**Comment by djwesto** [comment]
Cheers @GilesGibson. All good points here. I'll address each one in turn:

* The events map at http://dev-hernehill.gotpantheon.com/events/map isn't the same issue – please raise a new issue about this. @pmackay I've tried and am having the same problem with this.
* On the Venues page, I think the listing view should be a simple paged listing for now. @pmackay can you confirm this will be a paged list – with, say, 10–20 items displayed on each page?
* Over time, this view should probably also have filters or sorting tools added. If you'd like those, Giles, please could you add a new issue for this?
* As to your question about what happens when visitors click on a Venue pin, I'm not sure I understand you but I think the current behaviour is a good start – you get taken to the Venue's page. So, clicking the pin for Carnegie Library takes me to: http://dev-hernehill.gotpantheon.com/places/carnegie-library

Which looks like this:
![screenshot 2015-01-27 18 10 47](https://cloud.githubusercontent.com/assets/702685/5923995/d582b76e-a64f-11e4-88c2-bf1bee09f7d8.png)



@pmackay would it be possible to add a view showing all events happening in each Venue to every venue's landing page? It would essentially be the same view as on the Events landing page but filtered for only that Venue:



![screenshot 2015-01-27 18 12 14](https://cloud.githubusercontent.com/assets/702685/5924031/1131a8ce-a650-11e4-8594-6bb3539a95e1.png)

NB. Giles I don't think you've ever asked for Venues to feature opening times details so that's not currently in the Content Type for Venues. Can I suggest that if you want that to be added that it might be something we put in the Backlog for now and add in later – for now, the time that an Event is happening should obviously just be added into the Event which means the opening time of a Venue is less important.

Reassigned to @GilesGibson for responses.

**Comment by GilesGibson** [comment]
Happy for the click to go to the venue page, that would be fine.

**Comment by djwesto** [comment]
Assigning to @pmackay to check whether he thinks he has time to add the modified Events listing view to Venue node pages. If you can, mate, I will design a new layout for the Venue node pages to accommodate it.

**Comment by djwesto** [comment]
Actually, ignore that. I will create a new issue for this. But can you ensure there's paging on the Venues listing under the map @pmackay ?

**Comment by GilesGibson** [comment]
park the desire to add venue opening times. It can be via event for now.

**Comment by pmackay** [comment]
I've just pushed better pagers. Changed list from 10 to 20 and removed pager on map (which was a bug, map should show all pins).

Have moved #471 to backlog for now.

Assume otherwise this can be closed?

**Comment by djwesto** [comment]
Am just trying to enter enough real venues into the system so that we can actually see the pagers working. Takes a while... In the meantime, can you confirm whether the Places page at (dev-hernehill.gotpantheon.com/places) will ever appear on the live site once we launch? I clicked on the breadcrumb link just now and found the Places page which doesn't use the same approach as Venues:

![screenshot 2015-01-29 13 23 40](https://cloud.githubusercontent.com/assets/702685/5958209/1156d390-a7ba-11e4-89c9-f4518437def3.png)

I can do a layout for it but can you attach the same styling as in used on the Venues page? Alternatively, if users aren't supposed to be able to see /Places maybe we need to hide it from the Breadcrumbs trail? I can never remember the difference between Places and Venues...

**Comment by pmackay** [comment]
Venues can be Places or Businesses.

Places is not on the menu. We could disable page or just improve it.

**Comment by GilesGibson** [comment]
Through the haze of time `i seem to remember a convoluted discussion about places and venues. I think this was how it went:

A trader would list their shop as a place. Nice and simple.

A venue that only held events or activities (The Lido) would be listed as a venue, have information about it, where it was etc. 

There may be a case where a place was used as a venue - an event in the shop for instance.

I am therefore uncertain if we would need to display places at all? The map of local services would show where they are based. The map of events would show where they are taking place (venues). Would we need to show places?

I may have got this definition wrong, please correct.

**Comment by pmackay** [comment]
The map of services only shows businesses, not places.

People can create "Local business" or "Place" items on the site. Either of
those can be marked as a venue, to appear as available for events.

**Comment by GilesGibson** [comment]
So when would  we need to show "places" - would it be if someone wanted to find somewhere for an activity? Would it feed through to Connecting Communities - I would assume so. If displaying a map of places is possible then great. I would be happy to move to the v 1.01 list.

**Comment by djwesto** [comment]
Can I just double-check: if I create a "Place", then I assume it automatically becomes somewhere that I can run an event. Is that right? (i.e. I don't need to manually say it can be an Events Venue...)

**Comment by pmackay** [comment]
A Place has a boolean to be marked as venue, checked by default on the
form. But can be turned off.

**Comment by djwesto** [comment]
So if we're keeping the Places page I'll add a new issue to v1.01 for formatting the Places page so it matches the Venues page.

**Comment by GilesGibson** [comment]
OK, be good to capture the data for when people create a space, we can show it nicely a bit later.
