### ISSUE TITLE
Banner at the bottom of the page

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#494]
Is there a way of reducing the sheer size of the banner at the bottom of the page? Seems really dominant when the page is scrolled up?

Would a line or two suffice?

![image](https://cloud.githubusercontent.com/assets/6060985/6329061/0affc2e0-bb65-11e4-8a2d-af255b52450d.png)

**Comment by djwesto** [comment]
I *had* hoped that we'd be able to add more content into the footer area because right now it serves practically no function at all.

Ideally, we'd have a site map showing things like the main forum sections, main news and services categories etc in there which would help boost SEO a bit.

I haven't had any time to plan this out and I doubt @pmackay would have time to implement it for V1.0 now.

**Comment by GilesGibson** [comment]
any chance of at least making it smaller?

**Comment by pmackay** [comment]
Yes, as just mentioned in email sent :)
