### ISSUE TITLE
News item with newlines in text doesnt display so well

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#588]
![screen shot 2015-03-31 at 18 42 40](https://cloud.githubusercontent.com/assets/115115/6925200/ce671c24-d7d5-11e4-92a4-4a2b3eab07c4.png)

Any thoughts on how this could be handled better @djwesto ?

**Comment by djwesto** [comment]
I've said it before and I think I still stand by it: a summary field with a decent explanation next to it would help because it would give authors the chance to write a specific summary snippet which would go in that space properly. Simply chopping off a chunk of the main text is bound to lead to stuff like this happening because content authoring is a free-for-all. 

Another alternative would be to strip out and replace all line breaks with a full stop and a space but that would cause it's own problems. Anyone else got any suggestions? @gilesgibson?

**Comment by pmackay** [comment]
Best thing in that case is to use the summary of the body field then. But
we hid that a while back didnt we? :)

**Comment by GilesGibson** [comment]
I would like to try the summary line again, with some helpful prompting text to encourage its use. The current way is creating some interesting headlines.
@pmackay  Is it an easy fix?

**Comment by pmackay** [comment]
The simple fix is to un-hide the "Show summary" link that appears at the top of the news body. Do you want to do that @GilesGibson ?

**Comment by GilesGibson** [comment]
Can we have some explanatory text/prompting ext next to that field when the user edits it. It would explain where the summary field would appear on the main page and encourage users to write a simple X word headline/summary sort of thing.

**Comment by pmackay** [comment]
Only underneath the whole body field where the description goes...

**Comment by GilesGibson** [comment]
So, some way away from where the text gets entered? Not ideal at all. How come we managed to get some prompting text under the Image upload bit? That was at least close to where the information was needed.

**Comment by pmackay** [comment]
I'm seeing this as a duplicate of #480. Closing.
