### ISSUE TITLE
Google rankings

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#618]
new site

I have noticed that we have fallen off the scale on Google rankings. No mention at all at the moment which is a shame.

Do we just wait for traffic to build up or is there anything missing from the pages etc. Can we poke Google crawlers to pay a visit?

I think on the last site James spent a good time editing loads of pages to ensure that they all met Googles requirements for what they like to see and it got us on the front page (for "herne hill") and then up to third place. Just before the changeover we were second after wikipedia.

Given that according to google analytics search was the most common way people found us then this is of concern...

Would it be time to just re-direct everyone from the old site?
### Actions
- [x] Redirect old URL
- [ ] Ensure H1 tag displays properly on homepage
- [x] add alt tags to images
- [ ] see if JS/CSS can be combined any more
- [ ] check with Pantheon about IP canonicalisation
- [x] check libwww-perl
- [x] add social media links
- [x] want to use Google+?
- [ ] want to use Pinterest?
- [ ] see what microdata could be added
- [ ] test AdWords

**Comment by pmackay** [comment]
Have poked crawlers. Added you to Webmaster Tools so you can browse info there. 

Are you happy to just have an auto redirect from old site now?

Are there any other sites you know of that have a link to HH, and could update their URLs?

If you check the webmaster tools > Crawl > URL errors there are a number of user pages not found. That's because currently user pages can only be viewed if logged in. Are you happy for them to be visible if not logged in?

**Comment by djwesto** [comment]
I just ran a quick "Who links to me" type test via a web-based tool to see who is linking to the old HH Forum site. Here's a quick output I added to a Google Spreadsheet: 
https://docs.google.com/spreadsheets/d/1DCG0IKHZqZjyppP7Vqy-RPo1VeIdMb80Em3OexQEhMU/edit#gid=0

This list needs cleansing because many of the links (especially from Facebook) are contained in events listings which are for events which have already taken place, but the individual groups and traders could be contacted by @GilesGibson to encourage them to update main links.

In addition, all the existing traders and community groups with their own sites could also be encouraged to add a link to their site as well. In fact, something that's never occurred to me before is that @GilesGibson might want to consider drafting the wording for a small "badge" to go on their websites, providing a prominent link to the HH site – a sort of "I'm a Herne Hill Trader" badge... Give it some thought and I could put something together.

**Comment by GilesGibson** [comment]
@djwesto Thanks for doing the links list. An interesting collection. I will chase a few of them, the rest - mainly facebook, will slowly over time update themselves with new stories and links. It is a good idea to do a mailshot to any trader that has their own site to do a link back to HH. 

I like the idea of a digital badge. We could look at that, maybe tie in with a loyalty card promo again.

@pmackay I think we can do the auto-redirect now. Send the traffic over directly wherever possible.

I think we should, for now, keep user pages private to the site. Stops some spam crawlers from harvesting email addresses that may be left around. We can review later

**Comment by pmackay** [comment]
FYI, user pages shouldnt show emails anyway, even if public.

**Comment by GilesGibson** [comment]
agreed but users are users and often put stuff in, especially in what they think may be personal areas.

**Comment by djwesto** [comment]
Fair enough. If you find this is a problem I wonder if there's a module which will auto-obfuscate email addresses?

**Comment by GilesGibson** [comment]
the old site had an email scrambler. We used it in Forum posts. It caused a few support issues but I think most people got it.

**Comment by GilesGibson** [comment]
We are now not even in the first 12 pages on google for "herne hill". We used to be the second item on the front page. On the old site we used to be towards the bottom of the first page. Then James worked on the content (laying some of it out to be more google friendly), the way the pages were laid out etc and over a day or two we were up to fourth. 

Are we missing anything as it is frighteningly bad at the moment. Can we tell Google that we have moved and to pretend it is the same as before?

**Comment by pmackay** [comment]
Just noticed that searching for `herne hill forum` shows the new site as 3rd link, because the **name** of the site is `Herne Hill Forum` (different to domain). Do you want the name of the site to just be `Herne Hill`?

**Comment by GilesGibson** [comment]
I used to do a regular check on the SEO simply by entering "herne hill" as the search text. Before the site was switched we were number 2 after wikipedia. 

I would expect to be found if the search text was "herne hill forum".

As the site is more about Herne Hill than Herne Hill Forum, a strategic change we made then I suppose that we should name the site herne hill. 

The main issue is being found via search with the text "herne hill" in it somewhere. I am worried that we have dropped off the face of civilisation as we know it.

**Comment by pmackay** [comment]
Try "herne hill hustings" - you're number 2 link. Depends on what people
search for, and how good your pages are for SEO (which is down to page name
and content, as well as site config). All pages are now indexed.

**Comment by GilesGibson** [comment]
If it uses a specific text item, then we sometimes do OK. However, searching now for decorator herne hill means we don't come close. We used to be in top three. The traders liked this.It was true for loads of typical search criteria.

**Comment by pmackay** [comment]
I've added a few actions in a checklist. Couple of questions:
- do you want to have social media widgets on the homepage?
- Are you interested in G+ or Pinterest? Do you have a profile? 
- Has there been any FB activity related to the new site?
- Can you add alt tags to images more often?

FYI:
- The twitter feed is generating a lot of `herne hill forum` text items on the page, might alter things a bit.
- I've removed your email from footer as a scan suggested this was a bad idea, easy spam target.

And this is quite interesting: http://moz.com/search-ranking-factors

**Comment by pmackay** [comment]
As is this, more for local: http://moz.com/local-search-ranking-factors

**Comment by GilesGibson** [comment]
When you say social media widgets do you mean the twitter and facebook icons to trigger content to them? If so, yes, they are very useful to generate links to the page.

I dont think that HHForum has a profile on G+. There may have been something on Pinterest that I set up ages ago. Will it make a huge difference?

Alex has been putting loads on facebook, based from the new site.

We can but try and remind people (myself included) to add alt-tags to images. Unlikely to happen that often though.

I seem to remember on the old site that James went through every page sorting out page names etc. he also put in key content for google to find, not necessarily visible to users. I don't think he did the trick of white text on a white background stuff, Google clocked that a while back and demotes you.

Is it worth having a look at anything sneaky or clever on the old site?

**Comment by pmackay** [comment]
Have spent morning on this:
- have added old site to Analytics and registered "change of address"
- setup a permanent 301 redirect from old to new site
- cleaned up H1 tags on events sidebar list
- registered with Bing Tools and submitted sitemap
- changed URL on HH page on Wikipedia

I'm still not quite sure of the best way to represent the page header when its just an image. @djwesto any thoughts?

@GilesGibson recommend you make sure that all images shown on homepage at least have `alt` text.

Google ranking is now on 5th page. Lets monitor as these changes might take a few days to affect it.

Note that for keywords, `hernehillforum` still comes up more frequently than others on the homepage because of twitter feed.

**Comment by GilesGibson** [comment]
I have edited all the photos I can find and added in Alt-text. be interesting to see if anything changes in the rankings. Need to do something fast, getting really worrying. If the twitter feed can search all text for "herne hill" then better.

**Comment by pmackay** [comment]
![hh_google](https://cloud.githubusercontent.com/assets/115115/7338868/9e626156-ec51-11e4-81a0-4fe557ca03a0.png)

**Comment by pmackay** [comment]
![awesome](https://cloud.githubusercontent.com/assets/115115/7338870/bd3fa124-ec51-11e4-97c0-78fd844ece0e.gif)

**Comment by GilesGibson** [comment]
so what was the change that made the difference do you think?

**Comment by pmackay** [comment]
Setting up 301 redirects on the old site and telling google about the
change of address.

**Comment by GilesGibson** [comment]
Great. Now we just need to get it back into at least second position. More links, more traffic etc.

**Comment by pmackay** [comment]
Over to you then....
