### ISSUE TITLE
News editor formats to double spaced

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#672]
New site. 
Trying to edit a news story. I cannot get the editor to do standard line spacing. It is insisting on double spacing. Tried deleting everything in the news item and replacing with plain text via notepad - still leaves it in double spaced. 

Really frustrating for people, no idea why it will not allow single line spacing.

http://www.hernehill.org.uk/news/camra-crawl-closed-pubs-including-half-moon

**Comment by pmackay** [comment]
Have you any idea why this might have suddenly changed behaviour? I guess this wasnt happening before?

**Comment by GilesGibson** [comment]
This was an article written by someone else. I just tried to tidy it up, 30 minutes later, still trying. IS the default template double spaced?

**Comment by pmackay** [comment]
Fixed it. Have saved a new published version.

**Comment by GilesGibson** [comment]
what was the problem?
(and many thanks for fixing it)

**Comment by pmackay** [comment]
Somehow all the lines had got wrapped as paragraphs. Dont know why, maybe it was what it was pasted from. I copied the text and edited it as plain, removed the line breaks and put it back.

**Comment by GilesGibson** [comment]
I copied it all into wordpad and then pasted it back into what I thought was an empty description box. Should that not have stripped out all the formatting?

**Comment by pmackay** [comment]
I’m not sure Wordpad is a plain text editor. On a mac try Textedit.

**Comment by djwesto** [comment]
Hi Giles,

I'd actually recommend you avoid using TextEdit on a Mac – it offers rich text _and_ plain text editing and it's easy to miss the fact you're using the wrong mode. Better to use something like [Text Mate](http://macromates.com) that only offers plain text editing.

Having now launched CML, I've been working on content authoring in Drupal for quite some time and I can completely sympathise with the terrible out-of-the-box experience authors get when editing content in Drupal's rich text area. It takes time to optimise the experience and we still aren't there yet with CML, let alone building what we've learned back into OpenLocal but it's something I'd want to prioritise.

You didn't provide a screenshot so I can't see exactly what you mean but yes, many problems are introduced by pasting MS Word or other pre-formatted text into the rich text box on node edit forms.

I've been teaching Sandy to add text from MS Word using the "Paste Plain Text" or "Paste MS Word"  buttons, rather than simply pasting in directly from an MS Word doc. Sadly those are only visible once the second toolbar is twirled down by users so I don't expect anyone knows it's there:

![screenshot 2015-09-23 13 02 38](https://cloud.githubusercontent.com/assets/702685/10044534/b490d990-61f3-11e5-92ab-eef0b11da070.png)

This isn't too bad but it looks as if there are modules which can help with this and I suspect they're the way to go since you can't train everyone to use buttons to paste in content.

**Comment by djwesto** [comment]
This module would do it I think: https://www.drupal.org/project/pasteformat

**Comment by GilesGibson** [comment]
I used textedit on the mac. I had no idea it wasn't always plain text. If there could be some way to make it easier to get text to look reasonable it would be great. It is such a hassle fighting against the editor. I cannot believe that the technology isn't there yet. Seems very strange...

**Comment by pmackay** [comment]
Yeah, so ignore my last ramblings, and heed the advice of He Who Has Studied The Ways Of The Text Editors….

**Comment by djwesto** [comment]
Do not be so hard on yourself, young Padawan
